_target_: Dense4Dense.network.DeepDFT.DeepDFText0_Wrapper
name: 'LAGNet_big'
depth: 4
size_of_expansion: 20
num_features: 128
atom_embedding_size: 36
painn_column_cutoff: 3.
painn_column_min_value: 0.
painn_column_max_value: 3.
painn_column_basis: 'bessel'
deepdft_column0_cutoff: 3.
deepdft_column0_min_value: -0.5
deepdft_column0_max_value: 3.0
deepdft_column0_basis: 'bessel'
deepdft_column1_cutoff: 20.
deepdft_column1_min_value: -0.5
deepdft_column1_max_value: 20.
deepdft_column1_basis: 'fourier'
